"""
Profile perfumes.jsonl.zst -> DATA_DICTIONARY.md + viability verdict.
Streams the file; does not load it into memory.

    pip install zstandard
    python profile_dump.py data/raw/perfumes.jsonl.zst
"""
import io
import json
import pathlib
import sys
from collections import Counter



def records(path):
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                yield json.loads(line)


def dig(rec, path):
    """dig(rec, 'rating.average') -> value or None"""
    cur = rec
    for key in path.split("."):
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
    return cur


# field -> is it present/usable in this record?
CHECKS = {
    "year":              lambda r: r.get("year") is not None,
    "brand":             lambda r: bool(r.get("brand")),
    "notes.tiered":      lambda r: any(dig(r, f"notes.tiered.{t}") for t in ("top", "middle", "base")),
    "notes.flat":        lambda r: bool(dig(r, "notes.flat")),
    "accords":           lambda r: bool(r.get("accords")),
    "rating.average":    lambda r: dig(r, "rating.average") is not None,
    "rating.histogram":  lambda r: bool(dig(r, "rating.histogram")),
    "people":            lambda r: r.get("people") is not None,
    "relation":          lambda r: bool(r.get("relation")),
    "seasons":           lambda r: bool(r.get("seasons")),
    "price_value":       lambda r: dig(r, "price_value.average") is not None,
    "longevity":         lambda r: dig(r, "longevity.average") is not None,
    "community_gender":  lambda r: bool(r.get("community_gender")),
    "ai_summary.pros":   lambda r: bool(dig(r, "ai_summary.pros")),
    "ai_summary.cons":   lambda r: bool(dig(r, "ai_summary.cons")),
    "popularity":        lambda r: bool(r.get("popularity")),
    "gender":            lambda r: bool(r.get("gender")),
}


def main(path):
    n = 0
    have = Counter()
    notes = Counter()
    accords = Counter()
    years = Counter()
    brands = Counter()
    pros_words = Counter()
    notes_per_product = []
    ratings = []
    people_vals = []

    for rec in records(path):
        n += 1
        for field, test in CHECKS.items():
            try:
                if test(rec):
                    have[field] += 1
            except Exception:
                pass

        y = rec.get("year")
        if isinstance(y, int) and 1900 < y < 2030:
            years[y] += 1

        if rec.get("brand"):
            brands[rec["brand"]] += 1

        cnt = 0
        for tier in ("top", "middle", "base"):
            for note in (dig(rec, f"notes.tiered.{tier}") or []):
                if isinstance(note, dict) and note.get("name"):
                    notes[note["name"].strip().lower()] += 1
                    cnt += 1
        for note in (dig(rec, "notes.flat") or []):
            if isinstance(note, dict) and note.get("name"):
                notes[note["name"].strip().lower()] += 1
                cnt += 1
        notes_per_product.append(cnt)

        for acc in (rec.get("accords") or []):
            if isinstance(acc, dict) and acc.get("name"):
                accords[acc["name"].strip().lower()] += 1

        r = dig(rec, "rating.average")
        if isinstance(r, (int, float)):
            ratings.append(r)
        p = rec.get("people")
        if isinstance(p, int):
            people_vals.append(p)

        for item in (dig(rec, "ai_summary.pros") or []):
            if isinstance(item, dict) and item.get("text"):
                for w in item["text"].lower().split():
                    w = w.strip(".,;:!?()\"'")
                    if len(w) > 3:
                        pros_words[w] += 1

        if n % 20000 == 0:
            print(f"  ...{n:,}", flush=True)

    out = pathlib.Path("DATA_DICTIONARY.md")
    w = out.open("w")
    w.write(f"# Data Dictionary — `{pathlib.Path(path).name}`\n\n")
    w.write(f"Auto-generated by `profile_dump.py`. **{n:,} records.**\n\n")

    w.write("## Field coverage\n\n| field | present | % |\n|---|---|---|\n")
    for field in CHECKS:
        c = have[field]
        w.write(f"| `{field}` | {c:,} | {100*c/n:.1f}% |\n")

    npp = sorted(notes_per_product)
    w.write(f"\n## Shape\n\n")
    w.write(f"- Distinct brands: **{len(brands):,}**\n")
    w.write(f"- Distinct note tokens: **{len(notes):,}**\n")
    w.write(f"- Distinct accords: **{len(accords):,}**\n")
    w.write(f"- Notes per product: median **{npp[len(npp)//2]}**, "
            f"p10 {npp[len(npp)//10]}, p90 {npp[9*len(npp)//10]}\n")
    if ratings:
        rs = sorted(ratings)
        w.write(f"- rating.average: min {rs[0]:.2f}, median {rs[len(rs)//2]:.2f}, max {rs[-1]:.2f}\n")
    if people_vals:
        ps = sorted(people_vals)
        w.write(f"- people (raters): median **{ps[len(ps)//2]:,}**, "
                f"p90 {ps[9*len(ps)//10]:,}, max {ps[-1]:,}\n")

    if years:
        yr = sorted(years)
        recent = sum(c for y, c in years.items() if y >= 2015)
        w.write(f"\n## Years\n\n- Range **{yr[0]}–{yr[-1]}**, "
                f"{sum(years.values()):,} with a year ({100*sum(years.values())/n:.1f}%)\n")
        w.write(f"- Since 2015: **{recent:,}**\n\n| year | products |\n|---|---|\n")
        for y in [y for y in yr if y >= 2000]:
            w.write(f"| {y} | {years[y]:,} |\n")

    w.write("\n## Top 120 notes\n\n```\n")
    for tok, c in notes.most_common(120):
        w.write(f"{c:7d}  {tok}\n")
    w.write("```\n")

    w.write("\n## All accords\n\n```\n")
    for tok, c in accords.most_common():
        w.write(f"{c:7d}  {tok}\n")
    w.write("```\n")

    w.write("\n## Top 60 words in ai_summary.pros\n\n```\n")
    for tok, c in pros_words.most_common(60):
        w.write(f"{c:7d}  {tok}\n")
    w.write("```\n")

    # viability gate
    issues = []
    if have["year"] / n < 0.6:
        issues.append(f"year present on only {100*have['year']/n:.0f}% — trend axis will be thin")
    if have["relation"] / n < 0.3:
        issues.append(f"relation (have/want) on only {100*have['relation']/n:.0f}% — demand signal weakened")
    if have["ai_summary.pros"] / n < 0.15:
        issues.append(f"ai_summary.pros on only {100*have['ai_summary.pros']/n:.0f}% — sentiment component weak; "
                      "consider restricting analysis to products that have it")
    if len(notes) < 200:
        issues.append(f"only {len(notes)} distinct notes — taxonomy will be coarse")
    if years and sum(c for y, c in years.items() if y >= 2015) < 2000:
        issues.append("fewer than 2000 products since 2015 — momentum analysis thin")

    w.write("\n## Verdict\n\n" + ("**VIABLE** — no blockers.\n" if not issues else ""))
    for i in issues:
        w.write(f"- {i}\n")
    w.close()

    print(f"\n{n:,} records | {len(brands):,} brands | {len(notes):,} notes | {len(accords):,} accords")
    print("VERDICT:", "VIABLE" if not issues else "ISSUES")
    for i in issues:
        print("  !", i)
    print(f"-> wrote {out.resolve()}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])